### ISSUE TITLE
Getting rid of frames

### ISSUE THREAD

**Issue by haysga** [lulzimfazlija2/datejs#205]
Lulzim, we need to get rid of all of the frames in the current design.....in otherwords, the HTML needs to be loaded as a single page so that the experience is navigable on a phone....

Take a look at this image.....this is an unacceptable
![img_8680](https://cloud.githubusercontent.com/assets/5015809/17492624/9bea6496-5d7a-11e6-9e9c-a803272a5e54.PNG)
 experience for the students

**Comment by lulzimfazlija2** [comment]
Gerry i have been re-structing the student view and now seems quite better
on mobile. If you could check also from your iphone before we have the
skype call, try with an entrepreneur student.

Thnx

**Comment by haysga** [comment]
okay....i'll look...need to push back call to 10:30...talk then

Gerry A. Hays | Principal
Slane Capital Partners | 484 E. Carmel Drive #339 | Carmel, IN 46032
(P) 317.213.7542
www.slanecapital.com

**Comment by haysga** [comment]
Lulzim....need to deal with an issue at 11 so i don't think we have enough to talk...so let's chat at 12pmEST...txs -g

Gerry A. Hays | Principal
Slane Capital Partners | 484 E. Carmel Drive #339 | Carmel, IN 46032
(P) 317.213.7542
www.slanecapital.com

**Comment by lulzimfazlija2** [comment]
Np Gerry, will be here at that time.
